### ISSUE TITLE
Tema 2 Exercici 1: Error en els tests

### ISSUE THREAD

**Issue by GGP305** [bielr/matematica-discreta#9]
Bon dia,
Crec que és possible que hi hagi un error en els tests de l'exercici 1 del tema 2:
A l'[enunciat](https://github.com/bielr/matematica-discreta/blob/ace3f8a7624995756568e8f823e3949e3010e060/Entrega.java#L201), s'indica que hem de calcular el tamany del conjunt **_de parts_** de `(a u b) × (a \ c)`,
```java
     * Calculau el nombre d'elements del conjunt de parts de (a u b) × (a \ c)
```

mentre que al [test](https://github.com/bielr/matematica-discreta/blob/ace3f8a7624995756568e8f823e3949e3010e060/Entrega.java#L256) es comprova el tamany del conjunt `(a u b) × (a \ c)` (no el de parts):
```java
static void tests() {
      // Exercici 1
      // |(a u b) × (a \ c)|
```

Simplement agraïria saber quina de les dues coses hem de calcular per poder saber si s'han de modificar els tests o be l'enunciat i els calculs.

**Comment by bielr** [comment]
Hola, tens raó, l'error és a l'enunciat.
